### ISSUE TITLE
pertama load, tab dengan class active, konten tidak muncul

### ISSUE THREAD

**Issue by rafyakbar** [rafyakbar/evoting#2]
![screenshot 5](https://user-images.githubusercontent.com/22675316/34924746-d99019e4-f9d7-11e7-8843-c18155bc0c8b.png)
tapi ketika berpindah tab dan kembali lagi, baru muncul
![screenshot 6](https://user-images.githubusercontent.com/22675316/34924754-ee50e3a4-f9d7-11e7-862b-10264ace301e.png)

#malesdebugcss&js
file ada di file ada di resources\views\admin\public\votinghmj.blade.php

**Comment by BagasMuharom** [comment]
Itu bukan masalah css dan js nya

**Comment by rafyakbar** [comment]
trus gimana nge-fix kan nya??

**Comment by BagasMuharom** [comment]
Hapus class "fade in" pada tab pane pertama

**Comment by m1ku100** [comment]
saya juga begitu

**Comment by rafyakbar** [comment]
done, thanks gaes
