### ISSUE TITLE
DB Deploy

### ISSUE THREAD

**Issue by ifebry** [rafyakbar/evoting#4]
### 1. SQL Script
> Skrip import DB tolong dibuat dan dimasukkan dlm repo. Jadi nanti pas push ke repo lab, bisa dicoba langsung update DB di webserver.

### 2. Seed Default User/Admin
> Seed utk default user/admin user juga disediakan. Beda lokasi kerja, auth-key nya berbeda. Takutnya, di local jalan, di remote tidak.

**Comment by BagasMuharom** [comment]
Untuk skrip import db itu kita pakai migrasi nya Laravel bagaimana, pak ? Solnya sudah dibuatkan rafy
